name: javaleetcode
on: [push]
jobs:
  mvn-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jdk
          architecture: x64
      - name: Run maven clean verify
        run: mvn clean verify
      - name: Run tests
        run: mvn test
